# Generated by Django 4.2.5 on 2023-12-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ator',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='filme',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='diretor',
        ),
        migrations.DeleteModel(
            name='Nacionalidade',
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Diretor',
        ),
        migrations.DeleteModel(
            name='Filme',
        ),
    ]
